FROM node:16-alpine

# RUN yarn global add @quasar/cli
# RUN npm install -g @quasar/cli

# RUN npm install -g nodemon && npm install
# COPY . /
# CMD ["nodemon", "var/www"]
# WORKDIR /var/www
# COPY package.json .
#  RUN npm install --quiet
#  COPY . .
#  WORKDIR /var/www